# Generated by Django 5.2.6 on 2025-09-15 09:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Legal Name')),
                ('registration_number', models.CharField(max_length=100, verbose_name='Business Registration Number')),
                ('tax_id', models.CharField(max_length=50, verbose_name='Tax ID/EIN Number')),
                ('street_address', models.CharField(max_length=255, verbose_name='Street Address')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100, verbose_name='State/Province')),
                ('postal_code', models.CharField(max_length=20)),
                ('contact_person', models.CharField(max_length=255, verbose_name='Primary Contact Person')),
                ('contact_title', models.CharField(max_length=100, verbose_name='Contact Person Title')),
                ('company_phone', models.CharField(max_length=20, verbose_name='Company Phone Number')),
                ('business_email', models.EmailField(max_length=254, verbose_name='Business Email Address')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Company Website')),
                ('loan_products', models.JSONField(help_text='Stored as list of selected loan types', verbose_name='Types of Loans Offered')),
                ('min_loan_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Loan Amount')),
                ('max_loan_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum Loan Amount')),
                ('min_interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Minimum Interest Rate (%)')),
                ('max_interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Maximum Interest Rate (%)')),
                ('processing_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Processing Fee (%)')),
                ('late_payment_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Late Payment Fee')),
                ('min_loan_term', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)], verbose_name='Minimum Loan Term (months)')),
                ('max_loan_term', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)], verbose_name='Maximum Loan Term (months)')),
                ('lending_policies', models.TextField(verbose_name='Loan Approval Criteria & Policies')),
                ('bank_name', models.CharField(max_length=255)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('routing_number', models.CharField(max_length=20)),
                ('account_type', models.CharField(choices=[('checking', 'Checking Account'), ('savings', 'Savings Account'), ('business', 'Business Account')], max_length=20)),
                ('swift_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='SWIFT Code')),
                ('monthly_volume', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Expected Monthly Loan Volume')),
                ('years_in_business', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Years in Lending Business')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='Terms Accepted')),
                ('compliance_accepted', models.BooleanField(default=False, verbose_name='Compliance Acknowledged')),
                ('marketing_consent', models.BooleanField(default=False, verbose_name='Marketing Consent')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Registration Approved')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-date_registered'],
            },
        ),
    ]
