# Generated by Django 5.1.1 on 2025-10-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0004_loanapplication_approved_date_loanapplication_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('review', 'Under Review'), ('delinquent', 'Delinquent')], max_length=20),
        ),
    ]
