# Generated by Django 5.2.7 on 2025-11-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0006_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Registration Approved'),
        ),
    ]
