# Generated by Django 5.2.7 on 2025-11-28 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0007_alter_company_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='account_holder_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='company',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='monthly_volume',
        ),
        migrations.RemoveField(
            model_name='company',
            name='routing_number',
        ),
        migrations.RemoveField(
            model_name='company',
            name='swift_code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='years_in_business',
        ),
    ]
