# Generated by Django 5.2.7 on 2026-01-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0008_remove_company_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Interest rate %', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='term',
            field=models.PositiveIntegerField(blank=True, help_text='Loan term in months', null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='total_interest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='total_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('review', 'Under Review'), ('delinquent', 'Delinquent')], max_length=20),
        ),
    ]
