# Generated by Django 6.0.1 on 2026-01-19 09:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated')], max_length=15)),
                ('mobile_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('current_street_address', models.CharField(max_length=255)),
                ('current_city', models.CharField(max_length=100)),
                ('current_state', models.CharField(max_length=100)),
                ('current_postal_code', models.CharField(max_length=20)),
                ('permanent_street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_city', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_state', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed'), ('unemployed', 'Unemployed'), ('student', 'Student'), ('retired', 'Retired')], max_length=15)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('income_source', models.TextField()),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('application_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', max_length=20)),
                ('loan_product_type', models.CharField(blank=True, max_length=50, null=True)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('loan_term', models.PositiveIntegerField(blank=True, help_text='Loan term in months', null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Interest rate %', max_digits=5, null=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicate_check_hash', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
            options={
                'verbose_name': 'Borrower Application',
                'verbose_name_plural': 'Borrower Applications',
                'db_table': 'borrower',
                'ordering': ['-created_at'],
            },
        ),
    ]
