# Generated by Django 5.1.1 on 2025-10-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BorrowerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='security_answer_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='security_answer_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='security_question_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='security_question_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
