# Generated by Django 6.0.1 on 2026-01-19 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BorrowerApp', '0001_initial'),
        ('CompanyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowers', to='CompanyApp.company'),
        ),
        migrations.AddIndex(
            model_name='borrower',
            index=models.Index(fields=['email', 'company', 'date_of_birth'], name='borrower_email_837ccc_idx'),
        ),
    ]
