# Generated by Django 6.0.1 on 2026-01-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BorrowerApp', '0002_initial'),
        ('CompanyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='borrower',
            unique_together={('email', 'company')},
        ),
        migrations.AddIndex(
            model_name='borrower',
            index=models.Index(fields=['first_name', 'last_name', 'email'], name='borrower_first_n_92e0ca_idx'),
        ),
    ]
