# Generated by Django 6.0.1 on 2026-01-19 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BorrowerApp', '0003_alter_borrower_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='application_status',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='loan_amount',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='loan_product_type',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='loan_term',
        ),
    ]
